version: 2
env:
  - CGO_ENABLED=0

builds:
  -
    id: llm-to-anthropic
    binary: llm-to-anthropic
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.buildTime={{ .Date }}
      - -X main.gitCommit={{ .FullCommit }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm64
    overrides:
      - goos: linux
        ldflags:
          - -s -w -extldflags "-static"
          - -X main.version={{ .Version }}
          - -X main.buildTime={{ .Date }}
          - -X main.gitCommit={{ .FullCommit }}

archives:
  -
    builds:
      - llm-to-anthropic
    format_overrides:
      - goos: windows
        format: zip
    files:
      - "config.toml"
      - "README.md"
      - "LICENSE"

release:
  github:
    owner: nerdneilsfield
    name: llm-to-anthropic

dockers_v2:
  - id: llm-to-anthropic
    dockerfile: Dockerfile.goreleaser
    ids:
      - llm-to-anthropic
    image_templates:
      - nerdneilsfield/llm-to-anthropic:{{ .Tag }}
      - nerdneilsfield/llm-to-anthropic:latest
      - ghcr.io/nerdneilsfield/llm-to-anthropic:{{ .Tag }}
      - ghcr.io/nerdneilsfield/llm-to-anthropic:latest
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/nerdneilsfield/llm-to-anthropic/master/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"dengqi\",\"email\":\"dengqqi935@gmail.com\"}]"
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.description": "LLM API proxy with Anthropic compatibility. Supports OpenAI, Anthropic, Google Gemini, and more."
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.licenses": "MIT"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
