FROM alpine:3.20

ARG TARGETPLATFORM

RUN addgroup -S app && adduser -S app -G app
USER app

WORKDIR /app
COPY ${TARGETPLATFORM}/llm-to-anthropic /app/llm-to-anthropic
COPY config.toml /app/config.toml
COPY .env.example /app/.env.example

EXPOSE 8082

ENTRYPOINT ["/app/llm-to-anthropic"]
